kind = "web"
previewPath = "/"
title = "Crex Website"
version = "1.0.0"
id = "artifacts/crex-website"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19986

[services.development]
run = "pnpm --filter @workspace/crex-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/crex-website", "run", "build" ]
serve = "static"
publicDir = "artifacts/crex-website/dist"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19986"
BASE_PATH = "/"
